apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.2
    helm:
      valuesObject:
        installCRDs: true
        dns01RecursiveNameservers: 1.1.1.1:53,1.0.0.1:53
        dns01RecursiveNameserversOnly: true
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - 1.1.1.1
            - 1.0.0.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true