apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
    name: jellyfin
  namespace: jellyfin
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      resources:
        requests:
          cpu: 600m
          memory: 400Mi
        limits:
          memory: 800Mi
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin
          ports:
            - containerPort: 8096