apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: jellyfin-ingress
 namespace: jellyfin
 annotations:
  kubernetes.io/ingress.class: haproxy
spec:
 rules:
 - host: {{ .Values.hostname }}
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: jellyfin-svc
           port:
             number: 80