apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perconia-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.20.1
    chart: psmdb-db
  destination:
    server: "https://kubernetes.default.svc"
    namespace: revolt
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true