apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perconia-mongo-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.20.1
    chart: psmdb-db
    path: charts/psmdb-db/
    helm:
      valuesObject:
        replsets:
          - name: rs0
            size: 3
            expose:
              enabled: true
            resources:
              requests:
                cpu: "300m"
                memory: "0.5G"
              limits:
                cpu: "300m"
                memory: "0.5G"
            volumeSpec:
              pvc:
                resources:
                  requests:
                    storage: 3Gi
        sharding:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: revolt
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true