apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: "" 
  bgpInstances:
  - name: "haproxy-ingress"
    localASN: 65000
    peers:
    - name: "haproxy01"
      peerASN: 65000
      peerAddress: 10.199.10.1
      peerConfigRef:
        name: "cilium-peer"
    - name: "haproxy02"
      peerASN: 65000
      peerAddress: 10.199.10.2
      peerConfigRef:
        name: "cilium-peer"
    - name: "haproxy03"
      peerASN: 65000
      peerAddress: 10.199.10.3
      peerConfigRef:
        name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "PodCIDR"