apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: {{ .Values.initialPVSize }}