apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: immich-ml
 name: immich-ml
spec:
 replicas: 3
 selector:
   matchLabels:
     app: immich-ml
 template:
   metadata:
     labels:
       app: immich-ml
   spec:
      containers:
      - name: immich-ml
        image: ghcr.io/immich-app/immich-machine-learning:{{ .Values.immichVersion }}
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: immich-cm
                key: TZ
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: immich-pg-pguser-immich-pg-admin
                key: pgbouncer-uri
          - name: IMMICH_TELEMETRY_INCLUDE
            valueFrom:
              configMapKeyRef:
                name: immich-cm
                key: IMMICH_TELEMETRY_INCLUDE
        resources:
          limits:
            memory: 4000Mi
          requests:
            memory: 2000Mi
            cpu: 1000m
        ports:
        - containerPort: 3003
        livenessProbe:
          httpGet:
            path: /ping
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: immich-ml-svc
  labels:
    app: immich-ml
spec:
  selector:
    app: immich-ml
  ports:
  - name: immich-ml
    port: 3003
    targetPort: 3003
  type: ClusterIP