apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: valkey
 name: valkey
spec:
 replicas: 1
 selector:
   matchLabels:
     app: valkey
 template:
   metadata:
     labels:
       app: valkey
   spec:
     containers:
      - name: valkey
        image: {{ .Values.valkeyImage }}
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 5Mi
          requests:
            memory: 2Mi
            cpu: 10m
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 10