apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: valkey
 name: valkey
spec:
 replicas: 1
 selector:
   matchLabels:
     app: valkey
 template:
   metadata:
     labels:
       app: valkey
   spec:
     containers:
      - name: valkey
        image: {{ .Values.valkeyImage }}
        resources:
          limits:
            memory: 50Mi
          requests:
            memory: 20Mi
            cpu: 10m
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: immich-valkey
  labels:
    app: valkey
spec:
  selector:
    app: valkey
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  type: ClusterIP