apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: v1.17.7
    helm:
      valuesObject:
        #monitoring:
        #  enabled: true
        #  createPrometheusRules: true
        cephClusterSpec:
          mon:
            count: 3
            allowMultiplePerNode: false
          mgr:
            count: 2
            allowMultiplePerNode: false
          dashboard:
            enabled: true
            ssl: false
          placement:
            all:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: role
                          operator: In
                          values:
                            - storage-node
          storage:
            useAllNodes: false
            useAllDevices: false
            nodes:
              - name: "kube-work01.hyperpixel.net"
                devices:
                  - name: "/dev/disk/by-path/pci-0000:00:10.0-nvme-1"
              - name: "kube-work02.hyperpixel.net"
                devices:
                  - name: "/dev/disk/by-path/pci-0000:00:10.0-nvme-1"
              - name: "kube-work03.hyperpixel.net"
                devices:
                  - name: "/dev/disk/by-path/pci-0000:00:10.0-nvme-1"
            config:
              osdsPerDevice: '1'
        ingress:
          dashboard:
            host: 
              name: ceph.hyperpixel.net
              path: /
              pathType: Prefix
            annotations:
              kubernetes.io/ingress.class: haproxy
              cert-manager.io/cluster-issuer: cluster-issuer
            tls:
              - hosts:
                - ceph.hyperpixel.net
                secretName: testsecret-tls
        cephBlockPools:
          - name: ceph-blockpool
            spec:
              failureDomain: host
              replicated:
                size: 2
            storageClass:
              enabled: true
              name: ceph-block
              isDefault: false
              reclaimPolicy: Delete
              allowVolumeExpansion: true
        cephFileSystems:
          - name: ceph-filesystem
            spec:
              metadataPool:
                replicated:
                  size: 3
              dataPools:
                - failureDomain: host
                  replicated:
                    size: 2
              metadataServer:
                activeCount: 3
                activeStandby: true
            storageClass:
              enabled: true
              isDefault: true
              csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
              csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
              csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
              csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
              csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
              csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
              name: ceph-filesystem
              pool: data0
              reclaimPolicy: Delete
              allowVolumeExpansion: true
              volumeBindingMode: "Immediate"
        cephObjectStores:
          - name: ceph-objectstore
            spec:
              metadataPool:
                replicated:
                  size: 3
              dataPool:
                replicated:
                  size: 2
              gateway:
                instances: 3
                port: 80
            storageClass:
              enabled: true
              name: ceph-bucket
              reclaimPolicy: Delete
              volumeBindingMode: "Immediate"

              
          
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true