apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: volsync
    repoURL: https://charts.rook.io/release
    targetRevision: 0.13.0
    helm:
      valuesObject:
        monitoring: 
          enabled: true
        csi:
          serviceMonitor:
            enabled: true
        hostpathRequiresPrivileged: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: volsync
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true