apiVersion: v1
kind: Service
metadata:
 labels:
   run: echo-server
 name: echo-server-svc
spec:
 selector:
   run: echo-server
 ports:
 - name: port-1
   port: 80
   protocol: TCP
   targetPort: 8080