apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   run: vaultwarden
 name: echo-server
spec:
 replicas: {{ .Values.replicas }}
 selector:
   matchLabels:
     run: vaultwarden
 template:
   metadata:
     labels:
       run: vaultwarden
   spec:
     containers:
      - name: echo-server
        image: jmalloc/echo-server
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 5Mi
          requests:
            memory: 2Mi
            cpu: 10m