apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: {{ .Values.pvSize }}