apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: gitlab
    repoURL: https://charts.gitlab.io/
    targetRevision: 9.0.0
    helm:
      valuesObject:
        prometheus:
          install: false
        registry:
          enabled: false
        nginx-ingress:
          enabled: false
        certmanager:
          rbac:
            create: false
        gitlab-runner:
          rbac:
            create: false
        nginx-ingress:
          rbac:
            create: false
            createClusterRole: false
            createRole: false
        # prometheus:
        #   rbac:
        #     create: true
        installCertmanager: false
        redis:
          install: true
        postgresql:
          install: false
        global:
          pages:
            enabled: false
          registry:
            enabled: false
          edition: ce
          time_zone: America/Chicago
          application:
            create: true
          gitaly:
            enabled: true
          praefect:
            enabled: true
          hosts:
            domain: gitlab.hyperpixel.net
          minio:
            enabled: false
          ingress:
            configureCertmanager: false
            annotations:
              cert-manager.io/cluster-issuer: cluster-issuer
            class: haproxy
            provider: haproxy
            tls:
              secretName: gitlab-tls
          image:
            pullPolicy: IfNotPresent
          psql:
            host: 
            password:
              key:
              secret:
          hosts:
            https: true
          email:
            display_name: "Hyperpixel GitLab"
            from: "gitlab@hyperpixel.net"
            reply_to: "noreply@hyperpixel.net"
          appConfig:
            object_store:
              enabled: true
              proxy_download: true
              connection:
                secret: 
            defaultTheme: 3
            defaultColorMode: 2
            defaultSyntaxHighlightingTheme: 2
            incomingEmail:
              enabled: false
            defaultProjectsFeatures:
              builds: true
              containerRegistry: true
              issues: true
              mergeRequests: true
              snippets: true
              wiki: false
        gitlab-runner:
          install: false
        gitlab:
          gitaly:
            persistence:
              size: 50Gi
          gitlab-shell:
            enabled: false
          migrations:
            enabled: true
          sidekiq:
            enabled: true
            concurrenct: 10
            replicas: 3
            resources:
              requests:
                cpu: 50m
                memory: 300M
              limits:
                memory: 800M
          # toolbox:
          #   backups:
          webservice:
            enabled: true
            replicaCount: 3
            resources:
              requests:
                cpu: 100m
                memory: 1G
              limits:
                memory: 2G
            http:
              enabled: true
            
          
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true