apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://ansible-community.github.io/awx-operator-helm/
    targetRevision: 3.2.0
    chart: awx-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true