apiVersion: v1
kind: Service
metadata:
  name: linkwarden-svc
  labels:
    app: linkwarden
spec:
  selector:
    app: linkwarden
  ports:
  - name: linkwarden
    port: 80
    targetPort: 3000
  type: ClusterIP
