apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc
  labels:
    app: vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
  - name: vaultwarden
    port: 80
    targetPort: 3000
  type: ClusterIP
