apiVersion: v1
kind: Service
metadata:
 labels:
   app: minecraft
 name: minecraft-svc
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
  - name: port-1
    port: 25565
    protocol: TCP
    targetPort: 25565