apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: gitlab-dragonfly
  namespace: gitlab
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 750Mi

