apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: kubernetes
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    kubernetes:
      remoteNamespace: shared-secrets
      auth:
        serviceAccount:
          name: eso-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: eso-sa
    namespace: default
roleRef:
  kind: Role
  name: eso-role
  apiGroup: rbac.authorization.k8s.io